### ISSUE TITLE
Getting Errors when trying to run program

### ISSUE THREAD

**Issue by sammehrdad** [MortezaBashsiz/CFScanner#123]
every time I run the program  I get this error  .Net framework is installed on my machine and I have tried giving Administration access to the program. Still, unfortunately, It keeps showing this error. BTW thanks for helping people get access to free internet and flow of data

The error message is: Input string was not in a correct format  

System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at WinCFScan.frmMain.updateCFIPListStatusText() in C:\Users\Admin\Desktop\WinCFScan\WinCFScan\frmMain.cs:line 507
   at WinCFScan.frmMain.loadCFIPListView() in C:\Users\Admin\Desktop\WinCFScan\WinCFScan\frmMain.cs:line 457
   at WinCFScan.frmMain.oneTimeChecks() in C:\Users\Admin\Desktop\WinCFScan\WinCFScan\frmMain.cs:line 313
   at WinCFScan.frmMain.timerBase_Tick(Object sender, EventArgs e) in C:\Users\Admin\Desktop\WinCFScan\WinCFScan\frmMain.cs:line 191

Kind Regards

**Comment by smzm** [comment]
You run the script on Windows? 
You should run it on bash, which is available on Linux or mac. Although you can use WSL in windows tun run the script.

**Comment by goingfine** [comment]
try new release
