### ISSUE TITLE
خطای هندل نشده در لاگ اجرای پایتون

### ISSUE THREAD

**Issue by eloravpn** [MortezaBashsiz/CFScanner#372]
با پارامترهای زیر اجرا شده است:
`python3 cfFindIP.py --upload-test --threads 12 --config ./config-new.txt --download-speed 400  --upload-speed 200 --tries 3 --use-xray --subnets ./my-subnet.txt`

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/CFScanner/python/venv/lib/python3.9/site-packages/requests/models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/root/CFScanner/python/venv/lib/python3.9/site-packages/urllib3/response.py", line 624, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/root/CFScanner/python/venv/lib/python3.9/site-packages/urllib3/response.py", line 857, in read_chunked
    self._original_response.close()
  File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/root/CFScanner/python/venv/lib/python3.9/site-packages/urllib3/response.py", line 461, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: TimeoutError('Download/upload too slow!')", TimeoutError('Download/upload too slow!'))
```

**Comment by tempookian** [comment]
سپاس بابت اطلاع‌رسانی. لطفا بگید بعد از این ارور روند اجرا متوقف شد یا خیر. اگر متوقف نشده مشکل خاصی نیست و خب اون آیپی اوکی نبوده

**Comment by eloravpn** [comment]
درود
روند اجرا متوقف می شه و چند بار هم تست کردم
ممنونم🙏

**Comment by tempookian** [comment]
لطفا با نسخه جدید هم امتحان کنید و نتیجه رو اعلام کنید

**Comment by tempookian** [comment]
من این issue رو می‌بندم. ممنون می‌شم اگر با ورژن جدید هم تست کنید و اگر مشکلی بود issue جدید ایجاد کنید. سپاس
