### ISSUE TITLE
باگ در اسکن نسخه python

### ISSUE THREAD

**Issue by admiraltidebringer** [MortezaBashsiz/CFScanner#377]
با سلام و خسته نباشید
نسخه آخر ورژن python باگ داره. چند بار هم تست کردم. البته در نسخه های قبلی هم مشکلاتی نظیر این بود و نیاز به حل داره. با تشکر

NO 23.227.39.52    upload read timeout
NO 23.227.39.83    download error
NO 23.227.39.60    upload read timeout
NO 23.227.39.65    upload read timeout
NO 23.227.39.82    download error
NO 23.227.39.93    download error
NO 23.227.39.89    download error
NO 23.227.39.104   fronting connect timeout
NO 23.227.39.70    upload read timeout
NO 23.227.39.67    upload read timeout
NO 23.227.39.94    download error
NO 23.227.39.95    download error
NO 23.227.39.46    upload read timeout
NO 23.227.39.63    upload read timeout
NO 23.227.39.71    upload read timeout
NO 23.227.39.105   fronting connect timeout
NO 23.227.39.86    download unknown error
2023-04-08 10:03:00.258   cfscanner-python   [err] [23.227.39.86]   Download - unknown error
2023-04-08 10:03:00.258   cfscanner-python   [err] [   ]   ("Connection broken: TimeoutError('Download/upload too slow!')", TimeoutError('Download/upload too slow!'))
Traceback (most recent call last):
  File "/home/user/miniconda3/lib/python3.9/site-packages/urllib3/response.py", line 444, in _error_catcher
    yield
  File "/home/user/miniconda3/lib/python3.9/site-packages/urllib3/response.py", line 831, in read_chunked
    chunk = self._handle_chunk(amt)
  File "/home/user/miniconda3/lib/python3.9/site-packages/urllib3/response.py", line 775, in _handle_chunk
    value = self._fp._safe_read(amt)
  File "/home/user/miniconda3/lib/python3.9/http/client.py", line 626, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "/home/user/miniconda3/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/home/user/miniconda3/lib/python3.9/ssl.py", line 1242, in recv_into
    return self.read(nbytes, buffer)
  File "/home/user/miniconda3/lib/python3.9/ssl.py", line 1100, in read
    return self._sslobj.read(len, buffer)
  File "/home/user/CFScanner-1.1.8489.35707/python/cfFindIP.py", line 336, in _raise_speed_timeout
    raise TimeoutError("Download/upload too slow!")
TimeoutError: Download/upload too slow!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/miniconda3/lib/python3.9/site-packages/requests/models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/home/user/miniconda3/lib/python3.9/site-packages/urllib3/response.py", line 624, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/home/user/miniconda3/lib/python3.9/site-packages/urllib3/response.py", line 857, in read_chunked
    self._original_response.close()
  File "/home/user/miniconda3/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/user/miniconda3/lib/python3.9/site-packages/urllib3/response.py", line 461, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: TimeoutError('Download/upload too slow!')", TimeoutError('Download/upload too slow!'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/CFScanner-1.1.8489.35707/python/cfFindIP.py", line 397, in check_ip
    dl_speed, dl_latency = download_speed_test(
  File "/home/user/CFScanner-1.1.8489.35707/python/cfFindIP.py", line 284, in download_speed_test
    r = requests.get(
  File "/home/user/miniconda3/lib/python3.9/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/user/miniconda3/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/user/miniconda3/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/user/miniconda3/lib/python3.9/site-packages/requests/sessions.py", line 745, in send
    r.content
  File "/home/user/miniconda3/lib/python3.9/site-packages/requests/models.py", line 899, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
  File "/home/user/miniconda3/lib/python3.9/site-packages/requests/models.py", line 818, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: TimeoutError('Download/upload too slow!')", TimeoutError('Download/upload too slow!'))
NO 23.227.39.74    upload read timeout
NO 23.227.39.76    upload read timeout
NO 23.227.39.91    download unknown error

**Comment by tempookian** [comment]
سپاس بابت اطلاع‌رسانی. لطفا بگید بعد از این ارور روند اجرا متوقف شد یا خیر. اگر متوقف نشده مشکل خاصی نیست و خب اون آیپی اوکی نبوده

**Comment by admiraltidebringer** [comment]
سلام ممنون از شما بابت زحماتتون. نه متوقف نشد و ادامه پیدا کرد.

**Comment by tempookian** [comment]
سعی می‌کنم در آینده این ارور رو هم به لیست ارورها اضافه کنم که لاگ برنامه کثیف نباشه. باز هم ممنون که اطلاع دادید.
