### ISSUE TITLE
خط هنگام اجرا نسخه جدید پایتون در اندروید

### ISSUE THREAD

**Issue by ashaghal** [MortezaBashsiz/CFScanner#385]
نسخه جدید رو تست کردم در ubuntu 22.10 روی pc مشکلی نداشت و اجرا میشد. اما در userland روی اندروید خطای زیر داده میشد.
`
2023-04-09 05:40:42.605   xraybinary   [inf] [/home/userland/CFScanner/python/xray-linux-64]   Binary file already exists
2023-04-09 05:40:42.605   cfscanner-python   [inf] [   ]   Starting to scan 512 ips...
2023-04-09 05:40:48.280   cfscanner-speedtest   [err] [45.85.118.0]   Could not start proxy (v2ray/xray) service
2023-04-09 05:40:48.283   cfscanner-speedtest   [err] [   ]   Timeout exceeded for the port 37821 on host 127.0.0.1 to start accepting connections.
Traceback (most recent call last):
  File "/home/userland/CFScanner/python/utils/socket.py", line 33, in wait_for_port
    with socket.create_connection((host, port), timeout=timeout):
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/userland/CFScanner/python/speedtest/conduct.py", line 65, in test_ip
    process, proxies = start_proxy_service(
  File "/home/userland/CFScanner/python/xray/service.py", line 38, in start_proxy_service
    wait_for_port(host=proxy_listen, port=proxy_port, timeout=timeout)
  File "/home/userland/CFScanner/python/utils/socket.py", line 38, in wait_for_port
    raise TimeoutError(
TimeoutError: Timeout exceeded for the port 37821 on host 127.0.0.1 to start accepting connections.
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/userland/CFScanner/python/utils/socket.py", line 33, in wait_for_port
    with socket.create_connection((host, port), timeout=timeout):
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/userland/CFScanner/python/speedtest/conduct.py", line 65, in test_ip
    process, proxies = start_proxy_service(
  File "/home/userland/CFScanner/python/xray/service.py", line 38, in start_proxy_service
    wait_for_port(host=proxy_listen, port=proxy_port, timeout=timeout)
  File "/home/userland/CFScanner/python/utils/socket.py", line 38, in wait_for_port
    raise TimeoutError(
TimeoutError: Timeout exceeded for the port 37821 on host 127.0.0.1 to start accepting connections.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/userland/CFScanner/python/speedtest/conduct.py", line 74, in test_ip
    print_and_kill(ip=ip, message=message, process=process)
UnboundLocalError: local variable 'process' referenced before assignment
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/userland/CFScanner/python/cfscanner.py", line 78, in <module>
    for res in pool.imap(partial(test_ip, test_config=test_config, config_dir=CONFIGDIR), big_ip_list):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 873, in next
    raise value
UnboundLocalError: local variable 'process' referenced before assignment

**Comment by tempookian** [comment]
سپاس بابت اطلاع‌رسانی. مشکل برطرف شد لطفا به‌روزرسانی کنید. اگر مشکل همچنان پابرجا بود، لطفا یک issue جدید ایجاد کنید.
