### ISSUE TITLE
کرش اسکنر

### ISSUE THREAD

**Issue by Mohammad900** [MortezaBashsiz/CFScanner#532]
android.app.ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{57d1945 u0 ir.filternet.cfscanner/.service.CloudScannerService}
	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2040)
	at android.app.ActivityThread.access$2900(ActivityThread.java:277)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2265)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8282)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1074)

**Comment by 0ut0fCode** [comment]
با عرض سلام 

این خطا اغلب زمانی رخ میده که post notification در اندروید 12 به بالا به اپ اعطا نشه ! در نسخه بعدی سعی میکینم این خطا رو رفع کنیم اما به هرحال برای ادامه پیدا کردن پروسه اسکن با سرویس در پس زمینه به این مجوز نیاز هست ، در غیر این صورت با خاموش شدن صفحه گوشی یا حتی جابجا شدن بین صفحات اپ اسکن به طور غیر منتظره خاتمه پیدا میکنه .

با تشکر از گزارش خطا شما
