### ISSUE TITLE
ارور در پروسه اسکن با اسکنر پایتون

### ISSUE THREAD

**Issue by zeusking2004** [MortezaBashsiz/CFScanner#608]
سلام و خسته نباشید
وسط پروسه اسکن با اسکنر پایتون یکهو ارور میده و اسکن رو متوقف میکنه
ارورش هم این هستش .
Could not start xray service
تا قبلش کار میکنه و درست و دقیق اسکن میکنه اما یهو وسط کار اینو میده و اسکن متوقف میشه

**Comment by tempookian** [comment]
درود. 

از چه نسخه‌ای از اسکنر استفاده می‌کنید و روی چه سیستم عاملی؟
ممنون می‌شم اگر فایل لاگ اسکن رو هم ارسال کنید

**Comment by zeusking2004** [comment]
سلام
نسخه آخر اسکنر هستش به همراه کانکشن شخصی 
با استفاده از tmux در پس زمینه اجراش میکنم ولی بعد اسکن کردن 2 3 تا رنج خود به خود از کارمیفته و اروری ک گفتم رو میده 
[20230818_131638.log](https://github.com/MortezaBashsiz/CFScanner/files/12378062/20230818_131638.log)



ERROR:cfscanner.main:Error in starting xray service.
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/cfscanner/utils/socket.py", line 33, in wait_for_port
    with socket.create_connection((host, port), timeout=timeout):
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/cfscanner/speedtest/conduct.py", line 96, in test_ip
    process, proxies = start_proxy_service(
  File "/usr/local/lib/python3.8/dist-packages/cfscanner/xray/service.py", line 34, in start_proxy_service
    wait_for_port(host=proxy_listen, port=proxy_port, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/cfscanner/utils/socket.py", line 38, in wait_for_port
    raise TimeoutError(
TimeoutError: Timeout exceeded for the port 34507 on host 127.0.0.1 to start accepting connections.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.8/dist-packages/cfscanner/speedtest/conduct.py", line 103, in test_ip
    raise StartProxyServiceError(
cfscanner.utils.exceptions.StartProxyServiceError: Could not start xray service - 45.12.30.0
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/cfscanner/main.py", line 207, in main
    res = next(iterator)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
cfscanner.utils.exceptions.StartProxyServiceError: Could not start xray service - 45.12.30.0

**Comment by tempookian** [comment]
درود. حدسم اینه که تعداد thread رو بالا دادید. 
با
 -t 2
 امتحان کنید و ببینید آیا بهبودی حاصل می‌شه؟

**Comment by zeusking2004** [comment]
ممنونم از راهنماییتون
تست میکنم و نتیجرو بهتون اعلام میکنم
تعداد ترد 8 تا به صورت دیفالت در دانلود و در زمان اسکن نتایج به صورت آپلود ، با ترد 4 هستش

**Comment by zeusking2004** [comment]
سلام مجدد
مشکل با چیزی که اشاره کردین برطرف شد اما خب اینجوری سرعت اسکن خیلی پایینه 
تا چه حدی میتونم بالا ببرمش که مشکل پیش نیاد ؟ یا بستگی به پهنای باند سرور داره و باید تست بشه ؟

**Comment by tempookian** [comment]
> سلام مجدد مشکل با چیزی که اشاره کردین برطرف شد اما خب اینجوری سرعت اسکن خیلی پایینه تا چه حدی میتونم بالا ببرمش که مشکل پیش نیاد ؟ یا بستگی به پهنای باند سرور داره و باید تست بشه ؟

سلام. باید تست کنید. قانون قطعی‌ای براش نیست.
